### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Wikinger8** [Syncxv/vc-message-logger-enhanced#17]
Sometimes when I use this plugin my messages go blank
![Screenshot_2](https://github.com/Syncxv/vc-message-logger-enhanced/assets/85295145/f5137e4b-7622-4527-a216-e52067f677d3)
![Screenshot_1](https://github.com/Syncxv/vc-message-logger-enhanced/assets/85295145/f9d0c584-4871-4e01-91c2-fdf8dee79fb6)

**Comment by Syncxv** [comment]
should be fixed by: [dcea993](https://github.com/Syncxv/vc-message-logger-enhanced/commit/dcea993c14fe2d72532252e61c78e95f29db4154)

update and see if that works

**Comment by Wikinger8** [comment]
worked thx
