### ISSUE TITLE
Confusing updater message

### ISSUE THREAD

**Issue by D3SOX** [Syncxv/vc-message-logger-enhanced#2]
https://github.com/Syncxv/vc-message-logger-enhanced/blob/500210329fb8b60588fa6ab2d3e092265f1ea449/utils/checkForUpdates.ts#L63

I think this is kinda confusing because at first I thought it has automatically updated itself, but

<img src="https://github.com/Syncxv/vc-message-logger-enhanced/assets/24937357/b0a2e78d-9a28-406a-b96b-27a3357db68a" width="200" />

 I realized I had to pull and build manually. I'd suggest changing this message or including the info on how to update.

**Comment by Syncxv** [comment]
oh yeah i forgor we have that oops. should be more clear now. thanks!

updating automatically without editing vencord source code is probably impossible. 
Best solution i can think of is to write a bash script that inserts an import statement in the preload.
