### ISSUE TITLE
Prompts to "update" message logger when it's already updated

### ISSUE THREAD

**Issue by ScripterRickster** [Syncxv/vc-message-logger-enhanced#22]
I opened up Discord and saw that my message logger (a.k.a "message logger enhanced") needed to be updated. I proceeded to update it using the manual method. I re-opened discord and noticed that it still said that the message logger has an update even though it is already at the most recent version. I've verified that my message logger is at the latest version, so im not too sure if this is either the message logger's problem or an issue with vencord.

**Comment by Syncxv** [comment]
the plugin now has an updater, similar to vencords one. you dont need to manually update anymore.

in the most recent version you can go to the plugin settings and check for updates there:

![Discord_n5zkmKEDRk](https://github.com/Syncxv/vc-message-logger-enhanced/assets/47534062/d4249eb5-40b1-4fe1-b2ad-3957fd84fe48)
![Discord_OPUoUkuOX6](https://github.com/Syncxv/vc-message-logger-enhanced/assets/47534062/131f820a-d0cf-4fc3-abbb-6429950a01de)
