### ISSUE TITLE
Crashing discord

### ISSUE THREAD

**Issue by Tr3yWay996** [Syncxv/vc-message-logger-enhanced#23]
All other userplugins that i got dont crash discord but this one ? oh boy it does
please fix fr

**Comment by Syncxv** [comment]
its not crashing for me. try [updating](https://github.com/Syncxv/vc-message-logger-enhanced?tab=readme-ov-file#how-to-manually-update) or send a video of the crash

**Comment by Tr3yWay996** [comment]
> its not crashing for me. try [updating](https://github.com/Syncxv/vc-message-logger-enhanced?tab=readme-ov-file#how-to-manually-update) or send a video of the crash

Its already updated and the "video" would be discord loading, freezing, unfreezing, working, freezing, closing the ui and runing in the background, re opening, crashed
Here, full behavior of Vencord with this third party plugin even when hes solo in here

**Comment by Tr3yWay996** [comment]
> its not crashing for me. try [updating](https://github.com/Syncxv/vc-message-logger-enhanced?tab=readme-ov-file#how-to-manually-update) or send a video of the crash

And why marking it as closed anyway ? Its an issue and if i could have help with it from maybe other peoples and you instead of it being closed that'll be cool

**Comment by Syncxv** [comment]
i cant help you
