### ISSUE TITLE
Messages do not log to chat

### ISSUE THREAD

**Issue by dmandinec** [Syncxv/vc-message-logger-enhanced#31]
Hello, i have issue, that when message logger logs a message, it will stay in chat, but after restart it will disappear from chat, but it will stay in category logs. Is this a bug or is this a feature? Also images and gif will not log. Issues started after discord did "renaming". Thank you for your responses

**Comment by CatGirlDShadow** [comment]
Plugin is not yet updated to respect latest Discord changes. #29 opened to fix it.
