### ISSUE TITLE
Plugin causes crashes

### ISSUE THREAD

**Issue by Larvarus** [Syncxv/vc-message-logger-enhanced#32]
Apparently now the plugin will crash discord when you open the logs menu

**Comment by CatGirlDShadow** [comment]
Idk why this happens but this could easily be resolved by clearing all logs in settings.
Any data than you want to keep may be exported via same menu.

**Comment by Syncxv** [comment]
fixed here e13432adfbe3fb3e33c48ae06dd56cd784993a26

the new poll feature uses moment timestamps
