### ISSUE TITLE
Few bugs after a recent update.

### ISSUE THREAD

**Issue by gameshowrecaps** [Syncxv/vc-message-logger-enhanced#38]
The logs now shows every link that are not edited. It's also bugged on people who use Tupperbox.
![image](https://github.com/Syncxv/vc-message-logger-enhanced/assets/57842610/01bfc1ea-f14a-4c01-8591-c4d8263cee68)
![image](https://github.com/Syncxv/vc-message-logger-enhanced/assets/57842610/ebf013c4-b69d-4248-9198-07fdb5948bf8)

**Comment by Vendicated** [comment]
indeed, reverted https://github.com/Vendicated/Vencord/commit/799b903da94447bb6e62871977f1cd102cf9e06f
