### ISSUE TITLE
Issue with logging images

### ISSUE THREAD

**Issue by Draveyy** [Syncxv/vc-message-logger-enhanced#45]
Hi, i started to notice the logger is unable to log images which get deleted, all it leaves is just blurred preview of the image i assume? It does it with my messages too, it knows they were there but still only shows blurred loading

It doesnt happen all the time.

![image](https://github.com/user-attachments/assets/853ace5f-473e-408d-a9b8-f7f885a64a6e)
![image](https://github.com/user-attachments/assets/77398064-9580-4d25-a687-b19008a6b1e1)

![image](https://github.com/user-attachments/assets/c5f1f910-6b78-4370-ac98-71f68d4aaf51)

I tried recreating the issue, but I was unable to. Maybe its a me problem?

**Comment by MeatyChunks** [comment]
Seen this happen too, the images aren't saved to the image folder either. Wish I was able to add more info.

I am able to copy the link to the deleted image and it's just a plain png file with all the new attributes discord require to stop leeching, I wonder if that's something to do with it?

**Comment by Kumicoo** [comment]
Idk why no message logger is being updated frequently. All these devs just abandon them. One of the most wanted plugin groups, that just get abandoned. Devs probably hording the updated versions for themselves.

**Comment by comfortablemilk4454** [comment]
@Kumicoo fr. any alternatives that you know of? im gonna stop using this one as its just too buggy

**Comment by comfortablemilk4454** [comment]
@Syncxv this still happens to me with the latest message logger enhanced:

https://github.com/user-attachments/assets/6df6b610-dcd9-481b-9699-3e96d756dcc7

**Comment by comfortablemilk4454** [comment]
@Syncxv still happening, could it be because i'm on vesktop? ill try on official discord and see if it still happens but its at least broken on vesktop.
![CleanShot 2024-12-06 at 10 32 06@2x](https://github.com/user-attachments/assets/d215ff6c-01cb-4ada-b82a-f7526d478205)
![CleanShot 2024-12-06 at 10 32 15@2x](https://github.com/user-attachments/assets/b7d4eaab-56ca-4c49-b042-d888814f2232)

**Comment by comfortablemilk4454** [comment]
@Syncxv it happens on stable discord as well
