### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Kf637** [Syncxv/vc-message-logger-enhanced#49]
My Discord client keeps crashing when going to "Ghost Pinged"

https://github.com/user-attachments/assets/6fdb4395-6263-400c-8b51-d1b965f6d88d

![image](https://github.com/user-attachments/assets/566027e0-7c7b-41e4-b3d7-919d9147e9fa)

**Comment by Syncxv** [comment]
should be fixed here 40ae980 if not send the screenshot with the error in the console.
