### ISSUE TITLE
Not saving images

### ISSUE THREAD

**Issue by nerdysham** [Syncxv/vc-message-logger-enhanced#58]
MLE doesn't save attachements/images. i had an mp4 that was deleted, but all i saw was the blurred preview
![image](https://github.com/user-attachments/assets/418bfe06-e730-4178-bf97-6b8bdbe62593)

i can still download the image, since it links to a discord cdn link like so: 
https://media.discordapp.net/attachments/##############/############/blah.mp4

but the attachment itself is not downloaded? is this intended?

**Comment by Syncxv** [comment]
should be fixed here 199b24e but the attachment may have gone over the size limit.
![image](https://github.com/user-attachments/assets/349f768d-3f4c-4e39-8fee-8fa6bed6ffce)

**Comment by nerdysham** [comment]
Sorry for the late response. Just asking, is there a way to make the attachment size limit unlimited?
