### ISSUE TITLE
[Feature Request] Ignore bot message

### ISSUE THREAD

**Issue by c0re100** [Syncxv/vc-message-logger-enhanced#6]
We have ignore muted guilds/categories/channels, but bot haven't :\\
Since there are serval bots, it's not easy to blacklist bot  by manual.
So it should have a option to ignore bot messages.

**Comment by Syncxv** [comment]
you can ignore bots by going to the original message logger plugin and enabling it there. 
![image](https://github.com/Syncxv/vc-message-logger-enhanced/assets/47534062/8ecb83c8-03a0-403c-8cb2-95097b47fd5a)

**Comment by c0re100** [comment]
> you can ignore bots by going to the original message logger plugin and enabling it there. ![image](https://user-images.githubusercontent.com/47534062/279961056-8ecb83c8-03a0-403c-8cb2-95097b47fd5a.png)

oh, thank you! 
I thought it was independent configuration lol

**Comment by c0re100** [comment]
I guess it's missing one condition for whitelist server + ignore bot setting.

I've enabled ignore bots from the original message logger plugin.
![{64614682-600B-4EE2-B4C5-0123DA123EF8}](https://github.com/Syncxv/vc-message-logger-enhanced/assets/5726473/fe15fcf1-345c-43ec-b842-3a95f04db344)

But enhanced plugin is still logging bot delete/edit history on whitelisted server.
![{F86EA54F-C4AB-4F38-9535-DA710FBF8779}](https://github.com/Syncxv/vc-message-logger-enhanced/assets/5726473/de2b121a-540c-4b22-adbd-424236cdf066)

**Comment by Syncxv** [comment]
after you update you should see an option to ignore bots in message logger enhanced settings. enable that.

thanks for reporting.

commits:
[94aa371](https://github.com/Syncxv/vc-message-logger-enhanced/commit/94aa371f2c74d4fca0cfa6b1e55b7bf3eb6cb312)
[eece59d](https://github.com/Syncxv/vc-message-logger-enhanced/commit/eece59d28d8e59979de56cb6820d55e92c06852a)
